### PR TITLE
Request to Change Access Modifier of TokenSource for TokenCache Customization

### PR DESCRIPTION
**Pull request by tmdgusya**
Hello,

While attempting to customize our TokenCache, I encountered an issue with accessing TokenSource. Currently, TokenSource is defined with a package-private access modifier, which restricts its accessibility outside its package. This limitation poses a challenge in customizing TokenCache effectively.

Would it be possible to consider changing the access modifier of TokenSource to public? Making it publicly accessible would greatly enhance flexibility and facilitate custom implementations of TokenCache.

Thank you for considering this request. I believe this change could benefit other users facing similar customization needs.

### CODE REVIEW

**Comment by tmdgusya** [comment]
image

**Comment by tmdgusya** [comment]
@dimapasko Could you check my issue?

**Comment by dimapasko** [comment]
I'm fine with it. I just need some feedback from @yuriyostapenko since he is the author and has all the credentials to publish new package version.

**Review by dimapasko — APPROVED** [review]

**Comment by tmdgusya** [comment]
@yuriyostapenko Do you happen to know how long does it take to publish to maven repository?

**Pull request merged**
